'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {VEGETATION_KEY,validateAsset,type VegetationAsset} from '../vegetation/format';
import type {BakeSettings} from './bake';
import styles from './VegetationEditor.module.css';
export default function VegetationEditor(){
 const host=useRef<HTMLDivElement>(null),api=useRef<{generate:(s:BakeSettings)=>VegetationAsset;dispose:()=>void}|null>(null),asset=useRef<VegetationAsset|null>(null);
 const [settings,setSettings]=useState<BakeSettings>({seed:724,height:3.8,density:40,gnarl:.65}),[notice,setNotice]=useState('Загрузка редактора…'),[ready,setReady]=useState(false);
 useEffect(()=>{let stopped=false;import('./preview').then(({createPreview})=>{if(stopped||!host.current)return;api.current=createPreview(host.current);asset.current=api.current.generate({seed:724,height:3.8,density:40,gnarl:.65});setReady(true);setNotice('Low poly · 3 варианта деревьев · 4 дерева и до 110 пучков травы на участке 18 × 12 м.');}).catch(()=>setNotice('Не удалось загрузить редактор. Обновите страницу.'));return()=>{stopped=true;api.current?.dispose();};},[]);
 function generate(){try{asset.current=api.current?.generate(settings)??null;setNotice(`Готово: ${asset.current?.trees.map(t=>t.triangles).join(' / ')} треугольников на дерево. Геометрия запечена.`);}catch{setNotice('Не удалось собрать вариант. Уменьшите плотность.');}}
 function apply(){if(!validateAsset(asset.current))return;try{localStorage.setItem(VEGETATION_KEY,JSON.stringify(asset.current));setNotice('Сохранено для этого браузера. Откройте тестовый участок — игра загрузит готовую геометрию.');}catch{setNotice('Недостаточно места в браузере. Скачайте файл для сохранения.');}}
 function download(){if(!asset.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(asset.current)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='test-patch.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main className={styles.root}><div ref={host} className={styles.preview}/><aside className={styles.panel}><small>CYBERBASE / РЕДАКТОР КАРТЫ</small><h1>Растительность</h1><p>Предпросмотр трёх моделей, которыми засажена вся зона вылазок. Генерация выполняется только в редакторе.</p><b>LOW POLY · INSTANCING · WORLD CHUNKS</b>{([['seed','Seed',1,9999,1],['height','Высота дерева',2,5,.1],['density','Плотность листвы',8,60,1],['gnarl','Изгиб ветвей',0,1,.05]] as const).map(([key,label,min,max,step])=><label key={key}>{label}<span>{settings[key]}</span><input type="range" min={min} max={max} step={step} value={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:Number(e.target.value)}))}/></label>)}<button disabled={!ready} onClick={generate}>Сгенерировать и запечь</button><button disabled={!ready} onClick={apply}>Применить модели к зоне</button><button disabled={!ready} onClick={download}>Скачать готовые модели · JSON</button><button onClick={()=>{try{localStorage.removeItem(VEGETATION_KEY);setNotice('Восстановлен опубликованный вариант растительности.');}catch{setNotice('Хранилище недоступно.');}}}>Сбросить локальный вариант</button><Link href="/expedition?debug=1&vegetation=1">Открыть лесной участок в игре →</Link><Link href="/">← На базу</Link><p role="status">{notice}</p><footer><a href="https://github.com/achrefelouafi/VegetationGeneratorThreeJS" target="_blank" rel="noreferrer">VegetationGeneratorThreeJS</a> · MIT<br/>Деревья: mohamedachrefelouafi. Трава: CyberBase.<br/>Перетаскивание — обзор · колесо — масштаб.</footer></aside></main>;
}
