import * as T from 'three';
import {createPropLibrary,PROP_ASSETS,type PropId,type PropInstance} from './prop-assets';
import {fenceLength,animateCityProps} from './city-props';
import {elevationAt} from './world';
import type {Rect} from './config';
// v2 deliberately drops the early development placements. Those objects were
// quick catalogue tests and duplicated the authored expedition composition.
const KEY='netrunner.master.props.v2';
export type EditorState={instances:PropInstance[];selected:string|null;placing:boolean;notice:string};
export function createPropEditor(scene:T.Scene,onChange:(state:EditorState)=>void,anisotropy:number,height=elevationAt,onPads:(pads:Rect[])=>void=()=>{}){
 const library=createPropLibrary(anisotropy),root=new T.Group();root.name='MASTER · user placed environment props';scene.add(root);
 let instances:PropInstance[]=[],selected:string|null=null,active=false,placing=false,asset:PropId='barricade',rotation=0,length=3,ghost:T.Group|null=null,notice='Выберите объект, затем нажмите «Разместить».';
 const objects=new Map<string,T.Group>();
 const outline=new T.BoxHelper(new T.Object3D(),0xf3cc79);outline.visible=false;scene.add(outline);
 const emit=()=>onChange({instances:instances.map(i=>({...i})),selected,placing,notice});
 function refreshPads(){root.updateMatrixWorld(true);const pads:Rect[]=[];for(const obj of objects.values()){const bounds=new T.Box3().setFromObject(obj);if(!bounds.isEmpty())pads.push({x:(bounds.min.x+bounds.max.x)/2,z:(bounds.min.z+bounds.max.z)/2,w:bounds.max.x-bounds.min.x,d:bounds.max.z-bounds.min.z});}onPads(pads);}
 function save(){refreshPads();try{localStorage.setItem(KEY,JSON.stringify(instances));notice='Сохранено в этом браузере';}catch{notice='Не удалось сохранить: хранилище браузера недоступно';}emit();}
 function add(item:PropInstance){const model=library.create(item.asset,item.length);model.position.set(item.x,height(item),item.z);model.rotation.y=item.rotation*Math.PI/180;model.userData.instanceId=item.id;root.add(model);objects.set(item.id,model);}
 try{const data=JSON.parse(localStorage.getItem(KEY)??'[]');if(Array.isArray(data))for(const i of data.slice(0,200)){if(typeof i.id==='string'&&!objects.has(i.id)&&PROP_ASSETS.some(a=>a.id===i.asset)&&[i.x,i.z,i.rotation].every(Number.isFinite)&&i.x>=0&&i.x<=144&&i.z>=0&&i.z<=72){if(i.asset==='modular-fence')i.length=fenceLength(Number.isFinite(i.length)?i.length:3);instances.push(i);add(i);}}}catch{notice='Не удалось прочитать сохранённую карту';}
 refreshPads();
 function clearGhost(){if(ghost){scene.remove(ghost);ghost.traverse(o=>{if(o instanceof T.Mesh)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});ghost=null;}}
 function arm(){clearGhost();selected=null;outline.visible=false;placing=true;ghost=library.create(asset,length);ghost.traverse(o=>{if(o instanceof T.Mesh){o.material=(o.material as T.Material).clone();o.material.transparent=true;o.material.opacity=.58;o.castShadow=false;}});ghost.rotation.y=rotation*Math.PI/180;ghost.visible=false;scene.add(ghost);notice='Наведите курсор на карту · клик разместит объект · Esc отмена';emit();}
 function position(point:T.Vector3){const p=point.clone();if(asset!=='modular-fence')return p;const a=rotation*Math.PI/180,dx=Math.cos(a)*length/2,dz=-Math.sin(a)*length/2;let best=.65;for(const item of instances){if(item.asset!=='modular-fence')continue;const b=item.rotation*Math.PI/180,l=(item.length??3)/2;for(const end of [-1,1])for(const side of [-1,1]){const x=item.x+end*Math.cos(b)*l-side*dx,z=item.z-end*Math.sin(b)*l-side*dz,d=Math.hypot(x-point.x,z-point.z);if(d<best){best=d;p.x=x;p.z=z;}}}return p;}
 function select(id:string|null){placing=false;clearGhost();selected=id;const selectedItem=instances.find(i=>i.id===id);if(selectedItem){asset=selectedItem.asset;rotation=selectedItem.rotation;length=selectedItem.length??3;}const obj=id?objects.get(id):null;outline.visible=!!obj&&active;if(obj)outline.setFromObject(obj);emit();}
 emit();
 return {get active(){return active;},get placing(){return placing;},setActive(value:boolean){active=value;if(!active){placing=false;clearGhost();outline.visible=false;}emit();},setAsset(id:PropId){asset=id;if(placing)arm();},setLength(value:number){length=fenceLength(value);if(selected){const item=instances.find(i=>i.id===selected)!;if(item.asset!=='modular-fence')return;item.length=length;root.remove(objects.get(selected)!);add(item);outline.setFromObject(objects.get(selected)!);save();}else if(placing)arm();},setRotation(value:number){rotation=value;if(ghost)ghost.rotation.y=value*Math.PI/180;if(selected){const item=instances.find(i=>i.id===selected)!;item.rotation=value;objects.get(selected)!.rotation.y=value*Math.PI/180;outline.setFromObject(objects.get(selected)!);save();}},arm,select,cancel(){placing=false;clearGhost();notice='Размещение завершено';emit();},hover(point:T.Vector3){point=position(point);if(ghost){ghost.position.set(point.x,height(point),point.z);ghost.visible=point.x>=0&&point.x<=144&&point.z>=0&&point.z<=72;}},click(ray:T.Raycaster,point:T.Vector3){if(placing){point=position(point);if(point.x<0||point.x>144||point.z<0||point.z>72)return;if(instances.length>=200){notice='Лимит: 200 объектов. Удалите ненужные экземпляры.';emit();return;}const item={id:crypto.randomUUID(),asset,x:point.x,z:point.z,rotation,...(asset==='modular-fence'?{length}:{})};instances.push(item);add(item);save();}else{const hit=ray.intersectObjects(root.children,true)[0];let node:T.Object3D|undefined=hit?.object;while(node&&!node.userData.instanceId)node=node.parent??undefined;select(node?.userData.instanceId??null);}},remove(){if(!selected)return;const obj=objects.get(selected);if(obj)root.remove(obj);objects.delete(selected);instances=instances.filter(i=>i.id!==selected);selected=null;outline.visible=false;save();},stream(point:{x:number;z:number}){animateCityProps(root,performance.now()/1000);objects.forEach(o=>{o.position.y=height(o.position);o.visible=Math.hypot(o.position.x-point.x,o.position.z-point.z)<57;});},dispose(){clearGhost();scene.remove(root,outline);outline.geometry.dispose();(outline.material as T.Material).dispose();library.dispose();}};
}
