'use client';
import Image from 'next/image';
import {useState} from 'react';
import {CLASSES,type CombatClass} from './combat';
import {ITEMS,type LootKind} from '../expedition/config';
import {ATTRIBUTES,ATTRIBUTE_BUDGET,TALENT_BUDGET,DRAFT_KEY,GEAR,freshDraft,parseDraft,allocateAttribute,allocateTalent,spentTalents,type CharacterDraft} from './character-draft';
import {Glyph} from './GameHud';
import s from './CharacterPanel.module.css';
type Entry={id:string;name:string;rarity:string;icon:string;count:number;gear:boolean};
const rarityOrder=['COMMON','UNCOMMON','RARE','EPIC'];
export default function CharacterPanel({classId,hp,energy,cooldowns,stash,bag,initialTab}:{classId:CombatClass;hp:number;energy:number;cooldowns:number[];stash:Partial<Record<LootKind,number>>;bag:Partial<Record<LootKind,number>>;initialTab:'inventory'|'talents'}) {
 const [tab,setTab]=useState(initialTab),[filter,setFilter]=useState('all'),[sort,setSort]=useState('type');
 const [draft,setDraft]=useState<CharacterDraft>(()=>{try{return parseDraft(localStorage.getItem(DRAFT_KEY));}catch{return freshDraft();}});
 const [selected,setSelected]=useState('blade'),[notice,setNotice]=useState(''),[node,setNode]=useState([0,0]);
 const persist=(next:CharacterDraft)=>{setDraft(next);try{localStorage.setItem(DRAFT_KEY,JSON.stringify(next));setNotice('Draft saved in this browser');}catch{setNotice('Storage unavailable · changes last until this window closes');}};
 const entries:Entry[]=[...GEAR.map(g=>({...g,count:1,gear:true})),...(Object.keys(ITEMS) as LootKind[]).filter(k=>(stash[k]??0)>0).map(k=>({id:k,...ITEMS[k],count:stash[k]!,gear:false,icon:k==='batteries'?'bolt':k==='weapon_parts'?'sword':'bag'}))];
 const visible=entries.filter(e=>filter==='all'||(filter==='gear'?e.gear:!e.gear)).sort((a,b)=>sort==='rarity'?rarityOrder.indexOf(b.rarity)-rarityOrder.indexOf(a.rarity):sort==='name'?a.name.localeCompare(b.name,'en'):Number(b.gear)-Number(a.gear));
 const item=entries.find(e=>e.id===selected),points=ATTRIBUTE_BUDGET-draft.attributes.reduce((a,b)=>a+b,0),talentPoints=TALENT_BUDGET-spentTalents(draft);
 const skill=CLASSES[classId].skills[node[0]],nodeId=`${classId}.${node[0]}.${node[1]}`,rank=draft.talents[nodeId]??0;
 const talentNext=allocateTalent(draft,classId,node[0],node[1]);
 return <div className={s.shell}>
  <nav className={s.tabs} aria-label="Character section"><button aria-pressed={tab==='inventory'} onClick={()=>setTab('inventory')}>01 / CHARACTER & INVENTORY</button><button aria-pressed={tab==='talents'} onClick={()=>setTab('talents')}>02 / TALENT MATRIX <b>{talentPoints}</b></button></nav>
  <div className={s.notice}>TRAINING DRAFT <span>Equipment and point allocation are a local preview. Combat stats and loot remain live.</span></div>
  <div className={s.layout}>
   <section className={s.equipment}><div className={s.heading}><h3>Equipment</h3><span>{draft.equipped.length} / 4</span></div><div className={s.identity}><small>NR — 001 / ACTIVE OPERATIVE</small><h3>NEON SENTINEL</h3><span>{CLASSES[classId].name} · Level 1</span></div>
    <div className={s.portrait}><Image src="/game/ui/keeper.png" alt="Operative portrait" fill sizes="280px" unoptimized/><div className={s.slots}>{GEAR.map(g=><button key={g.id} title={`${g.slot}: ${draft.equipped.includes(g.id)?g.name:'empty'}`} aria-label={`${g.slot}: ${draft.equipped.includes(g.id)?g.name:'empty'}`} aria-pressed={selected===g.id} onClick={()=>{setSelected(g.id);setTab('inventory');}}><Glyph name={draft.equipped.includes(g.id)?g.icon:'spark'}/><small>{g.slot}</small></button>)}</div><span className={s.portraitLabel}>NEURAL SIGNATURE / VERIFIED</span></div>
    <div className={s.readout}><span>Health <b>{Math.ceil(hp)} / 100</b></span><meter min={0} max={100} value={hp} aria-label="Current health"/><span>Energy <b>{Math.floor(energy)} / 100</b></span><meter min={0} max={100} value={energy} aria-label="Current energy"/></div>
    <div className={s.summary}><span>Attribute points <b>{points}</b></span><span>Talent points <b>{talentPoints}</b></span></div><button className={s.reset} onClick={()=>{persist(freshDraft());}}>Reset equipment and points</button>
   </section>
   {tab==='inventory'?<section className={s.inventory}><div className={s.heading}><h3>Inventory</h3><span>{entries.length} / 30 slots</span></div><div className={s.toolbar}><div>{[['all','All'],['gear','Gear'],['loot','Resources']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><label>Sort<select aria-label="Inventory sorting" value={sort} onChange={e=>setSort(e.target.value)}><option value="type">Type</option><option value="rarity">Rarity</option><option value="name">Name</option></select></label></div>
    <div className={s.grid}>{visible.map(e=><button key={e.id} className={s.cell} data-rarity={e.rarity} aria-pressed={selected===e.id} aria-label={`${e.name}, ${e.count}${e.gear?', preview gear':''}`} title={`${e.name} · ${e.rarity}${e.gear?' · Preview gear':` · In stash: ${e.count}`}`} onClick={()=>setSelected(e.id)}><Glyph name={e.icon}/><small>{e.name}</small><b>{e.gear?(draft.equipped.includes(e.id)?'E':'◇'):`×${e.count}`}</b></button>)}{Array.from({length:Math.max(0,30-visible.length)},(_,i)=><div key={`empty${i}`} className={s.empty} aria-hidden="true">{String(visible.length+i+1).padStart(2,'0')}</div>)}</div>
    {!visible.length&&<p>No items in this category yet.</p>}
    <div className={s.inspector} aria-live="polite">{item?<><div><small>{item.rarity} / {item.gear?'PREVIEW GEAR':'BASE STASH'}</small><h3>{item.name}</h3><p>{item.gear?'Preview equipment slot. Combat bonuses are not applied yet.':`In stash: ${item.count}. Secured after extraction.`}</p></div>{item.gear&&<button onClick={()=>persist({...draft,equipped:draft.equipped.includes(item.id)?draft.equipped.filter(id=>id!==item.id):[...draft.equipped,item.id]})}>{draft.equipped.includes(item.id)?'Unequip':'Equip'}</button>}</>:<p>Select an item to inspect.</p>}</div>
    <div className={s.heading}><h3>Expedition Backpack</h3><span>NOT EXTRACTED</span></div><div className={s.bag}>{(Object.keys(ITEMS) as LootKind[]).filter(k=>(bag[k]??0)>0).map(k=><div key={k}><Glyph name="bag"/><span>{ITEMS[k].name}</span><b>×{bag[k]}</b></div>)}{!Object.values(bag).some(v=>v&&v>0)&&<p>Empty · find resources in the sector</p>}</div><p className={s.hint}>Loot reaches your base stash only after a successful extraction.</p>
   </section>:<section className={s.inventory}><div className={s.heading}><h3>Ability Matrix</h3><span>{talentPoints} SP</span></div><div className={s.classButtons}>{(Object.keys(CLASSES) as CombatClass[]).map(id=><button key={id} aria-pressed={classId===id} disabled={cooldowns.some(c=>c>0)} onClick={()=>window.dispatchEvent(new CustomEvent('netrunner:class',{detail:id}))}>{CLASSES[id].name}</button>)}</div><p className={s.hint}>Combat class can be changed after cooldowns finish. Every skill is already unlocked.</p>
    <div className={s.branches}>{CLASSES[classId].skills.map((ability,slot)=><section key={ability.name}><Glyph name={ability.icon}/><strong>{ability.name}</strong><small>{ability.cost} EN · {ability.cooldown} SEC</small>{['Power','Optimization','Mastery'].map((label,tier)=>{const r=draft.talents[`${classId}.${slot}.${tier}`]??0;return <button key={tier} aria-pressed={node[0]===slot&&node[1]===tier} onClick={()=>setNode([slot,tier])}><small>TIER 0{tier+1}</small><b>{label}</b><span>{'●'.repeat(r)}{'○'.repeat(5-r)}</span><small>{tier?'Requires rank 3 above':'Base module'}</small></button>;})}</section>)}</div>
    <div className={s.inspector}><div><small>MODULE 0{node[1]+1} / RANK {rank} OF 5</small><h3>{skill.name}</h3><p>{['Power','Optimization','Mastery'][node[1]]} · 1 SP per rank. Talent preview only; damage and cooldowns remain unchanged.</p></div><button disabled={talentNext===draft} onClick={()=>persist(talentNext)}>{rank===5?'Maximum rank':talentPoints===0?'No points':talentNext===draft?'Previous module required':'Invest 1 SP'}</button></div>
   </section>}
   <aside className={s.details}><div className={s.heading}><h3>Attributes</h3><span>{points} AP</span></div>{ATTRIBUTES.map((a,i)=><div className={s.attribute} key={a}><div><strong>{a}</strong><small>{['Physical power','Accuracy and reaction','Neural potential','Resilience'][i]}</small></div><b>{10+draft.attributes[i]}</b><button disabled={!points} aria-label={`Add: ${a}`} onClick={()=>persist(allocateAttribute(draft,i))}>+</button></div>)}<p className={s.hint}>Training allocation · base value 10.</p><div className={s.heading}><h3>Combat Stats</h3><span>LIVE</span></div><dl className={s.combat}><dt>Base damage</dt><dd>{CLASSES[classId].skills[0].damage}</dd><dt>Attack range</dt><dd>{CLASSES[classId].skills[0].range} m</dd><dt>Cooldown</dt><dd>{CLASSES[classId].skills[0].cooldown} sec</dd><dt>Energy regeneration</dt><dd>8 / sec</dd><dt>Maximum health</dt><dd>100</dd><dt>Maximum energy</dt><dd>100</dd></dl><p className={s.hint}>Live values for the current combat class.</p></aside>
  </div><footer className={s.footer}><span role="status">{notice||'Local draft · rewards and progression remain unchanged'}</span><span>I / ESC — CLOSE</span></footer>
 </div>;
}
