'use client';
import {useEffect,useState,useRef} from 'react';
import {CLASSES,type CombatClass} from './combat';
import {ITEMS,type LootKind} from '../expedition/config';
import styles from './GameHud.module.css';
import CharacterPanel from './CharacterPanel';
import {ASSET_URLS} from '../../src/assets/registry';
import {Glyph} from '../../src/ui/kit/Glyph';
export {Glyph};
function readStash():Partial<Record<LootKind,number>>{try{const data=JSON.parse(localStorage.getItem('netrunner.expedition.stash.v1')??'{}');const safe:Partial<Record<LootKind,number>>={};for(const key of Object.keys(ITEMS) as LootKind[])if(Number.isSafeInteger(data.bag?.[key])&&data.bag[key]>0)safe[key]=data.bag[key];return safe;}catch{}return {};}
const normalizePanel=(panel:string)=>({'Инвентарь':'Inventory','Древо талантов':'Talent Tree','Задания / Контракты':'Missions / Contracts','Настройки':'Settings'}[panel]??panel);
export default function GameHud({hidden=false,bag={},onSettings,onQuest,appearance='default'}:{appearance?:'default'|'ghost';hidden?:boolean;bag?:Partial<Record<LootKind,number>>;onSettings?:()=>void;onQuest?:()=>void}){
 const [stats,setStats]=useState({classId:'warrior' as CombatClass,hp:100,energy:100,cooldowns:[0,0,0,0]});
 const [menuOpen,setMenuOpen]=useState(false);
 const [panel,setPanel]=useState<string|null>(null),[stash,setStash]=useState<Partial<Record<LootKind,number>>>({});
 const modal=useRef<HTMLDivElement>(null),menuToggle=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const update=(e:Event)=>setStats((e as CustomEvent).detail);window.addEventListener('netrunner:stats',update);const open=(e:Event)=>{setStash(readStash());setPanel(normalizePanel((e as CustomEvent<string>).detail));};window.addEventListener('netrunner:panel',open);const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='Escape'){setPanel(null);setMenuOpen(false);}if(e.key.toLowerCase()==='i'&&!e.repeat){setStash(readStash());setPanel(p=>p==='Inventory'?null:'Inventory');}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('netrunner:stats',update);window.removeEventListener('netrunner:panel',open);window.removeEventListener('keydown',key);};},[]);
 useEffect(()=>{if(!panel)return;window.dispatchEvent(new Event('netrunner:input-reset'));const previous=document.activeElement as HTMLElement|null,menuButton=menuToggle.current;modal.current?.querySelector<HTMLButtonElement>('button')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const nodes=modal.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled),select:not(:disabled),input:not(:disabled),[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};window.addEventListener('keydown',trap);return()=>{window.removeEventListener('keydown',trap);if(previous&&previous!==document.body&&previous.getClientRects().length)previous.focus();else menuButton?.focus();};},[panel]);
 const classInfo=CLASSES[stats.classId];
 const characterPanel=panel==='Inventory'||panel==='Talent Tree';
 return <div className={`${styles.hud}${appearance==='ghost'?' '+styles.ghost:''}`}>
 {!hidden&&<><aside className={styles.character} aria-label="Character"><div className={styles.avatar} style={{backgroundImage:`url(${ASSET_URLS.ui.runnerAvatar})`}}><b aria-label="Level 1">1</b></div><div className={styles.vitals}><strong>NEON SENTINEL <small>{classInfo.name}</small></strong><div className={styles.bar} role="meter" aria-label="Health" aria-valuenow={stats.hp} aria-valuemin={0} aria-valuemax={100}><i style={{transform:'scaleX('+Math.max(0,Math.min(100,stats.hp))/100+')'}}/><span><em>HP</em>{Math.ceil(stats.hp)} / 100</span></div><div className={`${styles.bar} ${styles.energy}`} role="meter" aria-label="Energy" aria-valuenow={stats.energy} aria-valuemin={0} aria-valuemax={100}><i style={{transform:'scaleX('+Math.max(0,Math.min(100,stats.energy))/100+')'}}/><span><em>EN</em>{Math.floor(stats.energy)} / 100</span></div></div></aside>
 <nav className={styles.skills} aria-label="Four skills">{classInfo.skills.map((s,i)=><button key={s.name} title={`${s.name} · ${s.cost} energy · ${s.cooldown} sec`} aria-label={`${i+1} · ${s.name}`} disabled={stats.cooldowns[i]>0||stats.energy<s.cost||stats.hp<=0} onClick={()=>window.dispatchEvent(new CustomEvent('netrunner:cast',{detail:i}))}><kbd>{i+1}</kbd><Glyph name={s.icon}/><small>{s.cost||'•'}</small>{appearance==='ghost'&&<span className={styles.skillName}>{s.name}</span>}{stats.cooldowns[i]>0&&<b className={styles.cooldown}>{stats.cooldowns[i].toFixed(1)}</b>}</button>)}</nav>
 <button ref={menuToggle} className={styles.menuToggle} aria-label="Game menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><Glyph name="settings"/></button><nav className={`${styles.menu} ${menuOpen?styles.menuOpen:''}`} aria-label="Game menu">{[['Inventory','bag'],['Talent Tree','tree'],['Missions / Contracts','quest'],['Claim','bolt'],['Settings','settings']].map(([label,icon])=><button key={label} title={label} aria-label={label} onClick={()=>{if(label==='Settings'&&onSettings){onSettings();return;}if(label==='Missions / Contracts'&&onQuest){onQuest();return;}setMenuOpen(false);setStash(readStash());setPanel(label);}}><Glyph name={icon}/></button>)}</nav></>}
 {characterPanel&&<div className={styles.kitScrim} onPointerDown={e=>{if(e.target===e.currentTarget)setPanel(null);}}><CharacterPanel key={panel} panelRef={modal} onClose={()=>setPanel(null)} classId={stats.classId} hp={stats.hp} energy={stats.energy} cooldowns={stats.cooldowns} stash={stash} bag={bag} initialTab={panel==='Inventory'?'inventory':'talents'}/></div>}
 {panel&&!characterPanel&&<div className={styles.scrim} onPointerDown={e=>{if(e.target===e.currentTarget)setPanel(null);}}><div className={styles.modal} ref={modal} role="dialog" aria-modal="true" aria-labelledby="game-panel-title"><header><small>NEURAL LINK / CYBERBASE</small><button onClick={()=>setPanel(null)} aria-label="Close">×</button></header><h2 id="game-panel-title">{panel}</h2>
 {panel==='Claim'&&<><Glyph name="bolt"/><p>Quantum Charge · daily assignment.</p><p>The charging station is beyond the base bridge. Objectives and rewards will be connected later.</p><button disabled>Claim reward · unavailable</button></>}
 {panel==='Missions / Contracts'&&<><p>Expedition objective: explore the outskirts, collect resources, and extract.</p><p>Persistent contracts will be added later.</p></>}
 {panel==='Settings'&&<p>WASD — move · Shift — run · 1–4 — skills · E — interact · I — inventory.</p>}
 </div></div>}
 </div>;
}
