'use client';
import {useEffect,useState,useRef} from 'react';
import {CLASSES,type CombatClass} from './combat';
import {ITEMS,type LootKind} from '../expedition/config';
import styles from './GameHud.module.css';
export function Glyph({name}:{name:string}){
 const paths:Record<string,string>={sword:'M5 20L19 4l1 5L9 20M4 14l6 6M3 21l3-3',blades:'M3 3l17 18M21 3L4 21M3 15l6 6M15 21l6-6',burst:'M12 2v5M12 17v5M2 12h5M17 12h5M5 5l4 4M15 15l4 4M19 5l-4 4M9 15l-4 4',shield:'M12 3l8 3v6q0 6-8 10Q4 18 4 12V6zM12 8v8M8 12h8',spark:'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z',bolt:'M14 2L5 14h7l-2 8 9-14h-7z',target:'M8 12a4 4 0 1 0 8 0 4 4 0 1 0-8 0M12 2v5M12 17v5M2 12h5M17 12h5',bag:'M7 7V5q5-5 10 0v2M4 7h16v14H4zM4 12h16',tree:'M12 3v18M4 9h16M4 9v6M20 9v6M10 2h4v3h-4zM2 15h4v4H2zM18 15h4v4h-4z',quest:'M5 3h14v18H5zM9 8h6M9 12h6M9 16h4',settings:'M3 7h18M3 17h18M8 3v8M16 13v8'};
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]??paths.spark}/></svg>;
}
function readStash():Partial<Record<LootKind,number>>{try{const data=JSON.parse(localStorage.getItem('netrunner.expedition.stash.v1')??'{}');const safe:Partial<Record<LootKind,number>>={};for(const key of Object.keys(ITEMS) as LootKind[])if(Number.isSafeInteger(data.bag?.[key])&&data.bag[key]>0)safe[key]=data.bag[key];return safe;}catch{}return {};}
export default function GameHud({hidden=false,bag={},onSettings,onQuest}:{hidden?:boolean;bag?:Partial<Record<LootKind,number>>;onSettings?:()=>void;onQuest?:()=>void}){
 const [stats,setStats]=useState({classId:'warrior' as CombatClass,hp:100,energy:100,cooldowns:[0,0,0,0]});
 const [menuOpen,setMenuOpen]=useState(false);
 const [panel,setPanel]=useState<string|null>(null),[stash,setStash]=useState<Partial<Record<LootKind,number>>>({});
 const modal=useRef<HTMLDivElement>(null);
 useEffect(()=>{const update=(e:Event)=>setStats((e as CustomEvent).detail);window.addEventListener('netrunner:stats',update);const open=(e:Event)=>{setStash(readStash());setPanel((e as CustomEvent<string>).detail);};window.addEventListener('netrunner:panel',open);const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if(e.key==='Escape')setPanel(null);if(e.key.toLowerCase()==='i'&&!e.repeat){setStash(readStash());setPanel(p=>p==='Инвентарь'?null:'Инвентарь');}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('netrunner:stats',update);window.removeEventListener('netrunner:panel',open);window.removeEventListener('keydown',key);};},[]);
 useEffect(()=>{if(!panel)return;window.dispatchEvent(new Event('netrunner:input-reset'));const previous=document.activeElement as HTMLElement|null;modal.current?.querySelector<HTMLButtonElement>('button')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const nodes=modal.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};window.addEventListener('keydown',trap);return()=>{window.removeEventListener('keydown',trap);previous?.focus();};},[panel]);
 const classInfo=CLASSES[stats.classId];
 return <>
 {!hidden&&<><aside className={styles.character} aria-label="Персонаж"><div className={styles.avatar}><svg viewBox="0 0 60 70" aria-hidden="true"><path d="M5 62L9 27 30 4l21 23 4 35-25 7z" fill="#26352f" stroke="#91b795"/><path d="M16 27l14-9 14 9-3 22-11 12-11-12z" fill="#101d1c"/><path d="M20 33h7m6 0h7M22 46l8 5 8-5" stroke="#8fe6b1" strokeWidth="3"/></svg><b>1</b></div><div className={styles.vitals}><strong>NEON SENTINEL <small>{classInfo.name}</small></strong><div className={styles.bar} role="meter" aria-label="Здоровье" aria-valuenow={stats.hp} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${stats.hp}%`}}/><span>{Math.ceil(stats.hp)} / 100</span></div><div className={`${styles.bar} ${styles.energy}`} role="meter" aria-label="Энергия" aria-valuenow={stats.energy} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${stats.energy}%`}}/><span>{Math.floor(stats.energy)} / 100</span></div></div></aside>
 <nav className={styles.skills} aria-label="Четыре навыка">{classInfo.skills.map((s,i)=><button key={s.name} title={`${s.name} · ${s.cost} энергии · ${s.cooldown} с`} aria-label={`${i+1} · ${s.name}`} disabled={stats.cooldowns[i]>0||stats.energy<s.cost||stats.hp<=0} onClick={()=>window.dispatchEvent(new CustomEvent('netrunner:cast',{detail:i}))}><kbd>{i+1}</kbd><Glyph name={s.icon}/><small>{s.cost||'•'}</small>{stats.cooldowns[i]>0&&<b className={styles.cooldown}>{stats.cooldowns[i].toFixed(1)}</b>}</button>)}</nav>
 <button className={styles.menuToggle} aria-label="Игровое меню" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><Glyph name="settings"/></button><nav className={`${styles.menu} ${menuOpen?styles.menuOpen:''}`} aria-label="Игровое меню">{[['Инвентарь','bag'],['Древо талантов','tree'],['Задания / Контракты','quest'],['Claim','bolt'],['Настройки','settings']].map(([label,icon])=><button key={label} title={label} aria-label={label} onClick={()=>{if(label==='Настройки'&&onSettings){onSettings();return;}if(label==='Задания / Контракты'&&onQuest){onQuest();return;}setStash(readStash());setPanel(label);}}><Glyph name={icon}/></button>)}</nav></>}
 {panel&&<div className={styles.scrim} onPointerDown={e=>{if(e.target===e.currentTarget)setPanel(null);}}><div className={styles.modal} ref={modal} role="dialog" aria-modal="true" aria-labelledby="game-panel-title"><header><small>NEURAL LINK / CYBERBASE</small><button onClick={()=>setPanel(null)} aria-label="Закрыть">×</button></header><h2 id="game-panel-title">{panel}</h2>
 {panel==='Инвентарь'&&<><h3>Склад базы</h3><div className={styles.inventory}>{(Object.keys(ITEMS) as LootKind[]).map(k=><div key={k}><Glyph name="bag"/><span>{ITEMS[k].name}</span><b>{stash[k]??0}</b></div>)}</div><h3>Рюкзак вылазки</h3>{Object.entries(bag).length?Object.entries(bag).map(([k,v])=><p key={k}>{ITEMS[k as LootKind].name} × {v}</p>):<p>Пусто</p>}<p>Добыча переносится на склад после успешной эвакуации.</p></>}
 {panel==='Древо талантов'&&<><p>Выберите боевой класс. Смена доступна после завершения перезарядок.</p><div className={styles.classes}>{(Object.keys(CLASSES) as CombatClass[]).map(id=><button key={id} aria-pressed={stats.classId===id} disabled={stats.cooldowns.some(c=>c>0)} onClick={()=>window.dispatchEvent(new CustomEvent('netrunner:class',{detail:id}))}><Glyph name={CLASSES[id].skills[0].icon}/>{CLASSES[id].name}</button>)}</div><div className={styles.talents}>{classInfo.skills.map(s=><div key={s.name}><Glyph name={s.icon}/><strong>{s.name}</strong><small>Базовый навык открыт</small><span>│</span><button disabled>Улучшение · скоро</button></div>)}</div><p>Уровень 1. Прокачка и очки талантов появятся позже.</p></>}
 {panel==='Claim'&&<><Glyph name="bolt"/><p>Квантовый заряд · ежедневное задание.</p><p>Станция зарядки находится за мостом базы. Условия задания и получение награды будут подключены позже.</p><button disabled>Получить награду · недоступно</button></>}
 {panel==='Задания / Контракты'&&<><p>Цель вылазки: исследовать окраину, найти ресурсы и эвакуироваться.</p><p>Постоянные контракты появятся позже.</p></>}
 {panel==='Настройки'&&<p>WASD — движение · Shift — бег · 1–4 — навыки · E — взаимодействие · I — инвентарь.</p>}
 </div></div>}
 </>;
}
