'use client';
import {useState, type CSSProperties, type ReactNode} from 'react';
import AbilityMatrix from './ability-matrix';
import GhostSignal from './ghost-signal';
import {CLASSES, type CombatClass} from '../../components/game/combat';
import {landscapeRanges} from '../../components/expedition/landscape-state';
const screens = ['HUD','Character / Inventory','Landscape editor','Gap audit','Ability Matrix','GHOST SIGNAL'] as const;
const skillNames:Record<CombatClass,string[]> = {warrior:['Cleave','Combination','Quantum rift','Recovery'],mage:['Pulse','Neural spike','Wave','Regeneration'],ranger:['Shot','Piercing shot','EMP charge','Med capsule']};
const rarities = ['COMMON','UNCOMMON','RARE','EPIC'];
const gear = ['Monoblade MK.01','Neural visor','Kinetic armor','Servo boots'];
const gaps = [
 ['Foundation / Controls','Previewed','Scoped tokens, chamfers, buttons, meters and states.'],
 ['HUD','Adapted','Three classes and four skills. Static demonstration arena.'],
 ['Inventory / Loadout','Concept','Four rarity tiers; equipment selection is temporary.'],
 ['Abilities / Matrix','Adapted','Four current skills per class; conceptual upgrades, gated ranks and temporary sandbox points.'],
 ['ORACLE / Class Broker','Missing','Class switch is a preview control; broker states and reconfigure are absent.'],
 ['Dungeon','Missing','Floors, key cards, neural surge and cashout have no preview.'],
 ['Stake','Missing','No staking or wallet transaction flow.'],
 ['Dialogue','Missing','No NPC dialogue surface in this preview.'],
 ['Contracts','Missing','No contract board or reward claim flow.'],
 ['Screens: Abandon / Ranks / City','Missing','No confirmation, leaderboard or city overview screens.'],
 ['Landscape editor','Adapted','Existing parameter ranges; schematic concept, no terrain renderer.'],
 ['Rules','Previewed','Amber actions, semantic signals, opaque isolated chamfers, tabular data.'],
];
function Panel({title,children}:{title:string;children:ReactNode}) { return <section className="cb-cut cb-panel"><header className="cb-panel-hd"><h2>{title}</h2><span className="cb-sub">SANDBOX</span></header><div className="cb-panel-bd">{children}</div></section>; }
function Action({children,onClick,disabled=false}:{children:ReactNode;onClick:()=>void;disabled?:boolean}) {return <button className="cb-cut cb-btn" onClick={onClick} disabled={disabled}>{children}</button>;}
function Meter({label,value,color}:{label:string;value:number;color:string}) {return <div className="meter"><div><span>{label}</span><output>{value} / 100</output></div><div className="cb-bar cb-bar-seg" style={{'--v':`${value}%`,'--c':color} as CSSProperties}><i/></div></div>;}
export default function Preview(){
 const [screen,setScreen]=useState<typeof screens[number]>('HUD'),[classId,setClassId]=useState<CombatClass>('warrior');
 const [energy,setEnergy]=useState(100),[hp,setHp]=useState(76),[equipped,setEquipped]=useState(0),[selected,setSelected]=useState(0);
 const [notice,setNotice]=useState('Preview ready. All changes stay in this page.'),[terrain,setTerrain]=useState<Record<string,number>>({moss:.45,moisture:.6,density:.5,height:.4,wind:.2,relief:.6}),[patch,setPatch]=useState('North garden');
 const [saved,setSaved]=useState<Record<string,number>|null>(null);
 const switchClass=(id:CombatClass)=>{setClassId(id);setEnergy(100);setNotice(`${id[0].toUpperCase()+id.slice(1)} selected for preview.`);};
 return <main className="ui-kit-preview"><div className="preview-shell"><header className="preview-header"><div><p className="eyebrow">CYBERBASE / DESIGN LAB</p><h1>Runner’s instrument panel<span>UI kit preview</span></h1></div><span className="cb-chip">ISOLATED CONCEPT</span></header>
 <p className="intro">A playable interface study for Netrunner. Sample values, temporary state, no rewards or saved progression.</p>
 <nav aria-label="Preview surfaces" className="preview-tabs">{screens.map((s,i)=><button key={s} className={`cb-cut cb-btn ${screen===s?'cb-btn-primary':''}`} aria-pressed={screen===s} onClick={()=>setScreen(s)}><span className="data">0{i+1}</span>{s}</button>)}</nav>
 <div className="preview-toolbar"><span>RUNNER CLASS</span>{(['warrior','mage','ranger'] as const).map(c=><button key={c} className="class-choice cb-cut cb-btn" aria-pressed={classId===c} onClick={()=>switchClass(c)}>{c}</button>)}<span className="cb-chip">4 SKILLS · 4 RARITIES</span></div>
 {screen==='HUD'&&<div className="arena cb-cut"><div className="arena-grid" aria-hidden="true"/><div className="arena-title"><p className="eyebrow">REFUGE / SECTOR 07</p><h2>Systems online.</h2><p>Schematic environment · HUD concept</p></div><div className="hud-status cb-cut"><div className="runner-heading"><span className="runner-mark">N</span><div><small>NETRUNNER</small><h3>{classId}</h3></div><span className="data">LV 01</span></div><Meter label="Health" value={hp} color="var(--cb-tox)"/><Meter label="Energy" value={energy} color="var(--cb-ice)"/></div><div className="hud-objective cb-cut"><small>FIELD STATUS</small><h3>Explore the refuge</h3><p>Sample objective · no active contract</p><span className="data">07 : 24</span></div><div className="hud-bottom"><div className="skill-row">{CLASSES[classId].skills.map((s,i)=><button key={i} className="cb-cut cb-btn skill" disabled={energy<s.cost} onClick={()=>{setEnergy(v=>v-s.cost);if(s.heal)setHp(v=>Math.min(100,v+s.heal!));setNotice(`${skillNames[classId][i]} simulated. Cooldown ${s.cooldown}s shown as reference.`);}}><span className="skill-art" aria-hidden="true"/><kbd>{i+1}</kbd><b>{['╱','⌁','✣','+'][i]}</b><span>{skillNames[classId][i]}</span><small className="data">{s.cost} EN / {s.cooldown}s</small></button>)}</div><Action onClick={()=>{setEnergy(100);setHp(76);setNotice('Vitals reset.');}}>Reset vitals</Action></div></div>}
 {screen==='Character / Inventory'&&<div className="character-grid"><Panel title="Character"><div className="silhouette" aria-hidden="true">◇<span>╱│╲</span><span>╱ ╲</span></div><h3 className="class-label">{classId}</h3><p className="muted">Loadout concept · fitting room only</p><dl className="stats">{[['Strength',12],['Agility',8],['Intellect',6],['Endurance',10]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></Panel><Panel title="Inventory"><p className="muted">Select an item to inspect its rarity and equip it.</p><div className="inventory-grid">{gear.map((g,i)=><button key={g} className="item cb-cut" aria-pressed={selected===i} onClick={()=>setSelected(i)} style={{'--rarity':`var(--cb-r${i})`} as CSSProperties}><span className="item-glyph">{['╱','◎','◇','⌁'][i]}</span><span>{g}</span><small>{rarities[i]}</small>{equipped===i&&<em>Equipped</em>}</button>)}</div><div className="item-detail cb-cut"><p className="eyebrow">ITEM INSPECTION / CONCEPT</p><h3>{gear[selected]}</h3><p style={{color:`var(--cb-r${selected})`}}>{rarities[selected]}</p><p>Illustrative equipment; no combat modifier is applied.</p><Action disabled={equipped===selected} onClick={()=>{setEquipped(selected);setNotice(`${gear[selected]} equipped in the preview.`);}}>{equipped===selected?'Equipped':'Equip in preview'}</Action></div></Panel></div>}
 {screen==='Landscape editor'&&<div className="landscape-grid"><Panel title="Soil studio"><label className="field">Landscape patch<select value={patch} onChange={e=>setPatch(e.target.value)}><option>North garden</option><option>East verge</option></select></label><p className="muted">Concept controls using current landscape ranges. Shared sample settings; no terrain is published.</p>{Object.entries(terrain).map(([key,value])=>{const [min,max,step]=landscapeRanges[key as keyof typeof landscapeRanges];return <label className="field" key={key}><span>{key}<output>{value.toFixed(2)}</output></span><input aria-label={key} type="range" min={min} max={max} step={step} value={value} onChange={e=>setTerrain({...terrain,[key]:Number(e.target.value)})}/></label>;})}<div className="actions"><Action onClick={()=>{setSaved({...terrain});setNotice('Snapshot saved in page memory.');}}>Save snapshot</Action><Action disabled={!saved} onClick={()=>{if(saved)setTerrain({...saved});setNotice('Snapshot restored.');}}>Restore</Action></div></Panel><Panel title="Patch overview"><div className="terrain-map" style={{'--density':terrain.density,'--moss':terrain.moss} as CSSProperties}><div className="terrain-patch"/><span>{patch}</span><span className="map-road">PROTECTED ROAD</span></div><div className="map-legend"><span>● Soil / moss coverage</span><span>— Protected corridor</span></div><p className="muted">Schematic responds to moss and density. Other sliders demonstrate controls only.</p></Panel></div>}
 <div hidden={screen!=='Ability Matrix'}><AbilityMatrix classId={classId} names={skillNames[classId]}/></div>
 {screen==='GHOST SIGNAL'&&<GhostSignal/>}
 {screen==='Gap audit'&&<Panel title="Specification coverage"><p className="muted">Coverage of this isolated preview, not an audit of production feature availability.</p><div className="audit-list">{gaps.map(([name,status,description])=><article key={name}><div><h3>{name}</h3><span className={`audit-status status-${status.toLowerCase()}`}>{status}</span></div><p>{description}</p></article>)}</div><details><summary>Handoff adaptations</summary><p>Warrior / Mage / Ranger replace the source class naming. COMMON / UNCOMMON / RARE / EPIC replace the six-tier rarity ladder. Amber frame artwork is reserved for interactive skill buttons. Neutral panels use the one-chamfer primitive. English skill labels translate current combat data.</p></details></Panel>}
 <footer className="preview-footer"><p role="status" aria-live="polite">{notice}</p><span className="data">UI STUDY / 01</span></footer></div></main>;
}

